version: '2.1'
services:
  nginx:
    build:
      context: nginx
  #    args:
   #     uid: ${UID}
    #container_name: ${NGINX_CONTAINER_NAME}
    depends_on:
      - php-fpm
    volumes:
      - ../www:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"

  php-fpm:
    build:
      context: ./fpm
    volumes:
      - ../www:/var/www
    #depends_on:
     # - postgres