version: '2.1'
services:
  postgres:
    restart: always
    build:
      context: ./postgres
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}

  php-fpm:
    build:
      context: ./fpm
    volumes:
      - ../www:/var/www
    depends_on:
      - postgres

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../www:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm